/**
 * 
 */
package iva.server.categoryextractor.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Data structure for storing DBpedia page data
 * @author Aron
 */
public class DBpediaPage implements Serializable {
	private static final long serialVersionUID = 7857430085578080989L;
	
	private String name;
	private String source;
	private double score;
	private Set<String> categories = new HashSet<>();
	private Set<String> pageLinks = new HashSet<>();
	
	public DBpediaPage() {
	}
	
	public DBpediaPage(String name) {
		this.setName(name);
	}
	
	public DBpediaPage(String name, String source) {
		this(name);
		this.setSource(source);
	}

	public String getName() {
		return name;
	}

	public void setName(String categoryName) {
		this.name = categoryName;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public double getScore() {
		return score;
	}

	public void setScore(double score) {
		this.score = score;
	}

	public Set<String> getCategories() {
		return categories;
	}

	public void setCategories(Set<String> categories) {
		this.categories = categories;
	}
	
	public void addCategory(String category) {
		this.categories.add(category);
	}
	
	public Set<String> getPageLinks() {
		return pageLinks;
	}
	
	public void setPageLinks(Set<String> pageLinks) {
		this.pageLinks = pageLinks;
	}
	
	public void addPageLink(String pageLink) {
		this.pageLinks.add(pageLink);
	}

	/* (non-Javadoc)
	 * Auto generated by Eclipse using name and source fields.
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((source == null) ? 0 : source.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * Auto generated by Eclipse using name and source fields.
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DBpediaPage other = (DBpediaPage) obj;
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		if (source == null) {
			if (other.source != null) {
				return false;
			}
		} else if (!source.equals(other.source)) {
			return false;
		}
		return true;
	}
	
}
